version: '3'
services:
  rabbit:
    image: rabbitmq:3-management
    hostname: rabbit
    ports:
      - 5672:5672
      - 15672:15672
  db:
    image: "postgres:9.4"
    hostname: db
    ports:
      - 5432:5432
  redis:
    image: redis
    ports:
      - 6379:6379
  image_processor:
    build: ./image_processor
    command: ruby /application/image_processor.rb
    volumes:
      - ./image_processor:/application
    links:
      - db
      - redis
      - rabbit
    depends_on:
      - rabbit
      - worksheet_registry
    ports:
      - 4340:4340
    hostname: image_processor
  worksheet_registry:
    build: ./worksheet_registry
    command: bundle exec rails s -b 0.0.0.0 -p 4330
    volumes:
      - ./worksheet_registry:/application
    links:
      - db
      - redis
      - rabbit
    ports:
      - 4330:4330
    hostname: worksheet_registry
